### ISSUE TITLE
Hydrogen indexing issue when exporting from QM jobs

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-benchmark#42]
Sometimes I get results like this when exporting from QM compute:

<img width="555" alt="Screen Shot 2021-01-25 at 10 13 08 AM" src="https://user-images.githubusercontent.com/16329175/105747827-2293a800-5ef6-11eb-8ef1-37f41192d0cf.png">

The geometry is reasonable but the connectivity table (at least as pymol sees it) might be mangled. 

This is particularly confusing because both initial and final MM energies (during a minimization that STARTS from this structure) are reasonable: 

```
>  <initial_energy>  (1) 
-13.078687136788444 kilocalorie / mole

>  <final_energy>  (1) 
-23.499628545727884 kilocalorie / mole
```

If the indexing really were mangled I'd expect the initial energy to be very high.

**Comment by jthorton** [comment]
I think the cause of this is the use of `Molecule.from_smiles` [here](https://github.com/openforcefield/openff-benchmark/blob/6f3fd96ac0301c00f3bb72d1139756ada7ba16aa/openff/benchmark/geometry_optimizations/compute.py#L424)  instead of `Molecule.from_mapped_smiles` this code path is only followed however if users do a direct optimization using qcengine and skip the qcarchive server which should only effect compute procedures C and E.
